Repository MicrosoftDocs/sccm-docs-powershell-ref, pull requests merged in 2019-07, with the labels that each got.

#79 Added Scripting Example
  sccm-ps/ConfigurationManager/Export-CMTaskSequence.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, ready-to-merge

#80 Filled in the missing example
  sccm-ps/ConfigurationManager/Get-CMDistributionPointInfo.md
Labels: Change sent to author, do-not-merge, qualifies-for-auto-merge

#81 Update Get-CMBaselineDeploymentStatus.md
  sccm-ps/ConfigurationManager/Get-CMBaselineDeploymentStatus.md
Labels: Change sent to author, do-not-merge, qualifies-for-auto-merge

#82 Update Get-CMBaselineDeployment.md
  sccm-ps/ConfigurationManager/Get-CMBaselineDeployment.md
Labels: Change sent to author, do-not-merge, qualifies-for-auto-merge

#92 Added PowerShell examples and fixed Related Links format.
  sccm-ps/ConfigurationManager/Remove-CMPackageDeployment.md
Labels: Change sent to author, configmgr-other/tech, configuration-manager/prod, qualifies-for-auto-merge, ready-to-merge, review-team-triage
